#!/bin/bash
export LANG='en_US.UTF-8'

color_title="\e[1;38;5;4m"
color_subtitle="\e[38;5;5m"
color_success="\e[38;5;2m"
color_warning="\e[38;5;3m"
color_danger="\e[38;5;1m"
text_bold="\e[1m"
text_italic="\e[3m"
ansi_reset="\e[0m"

paste <(. ./scripts/top/left) <(. ./scripts/top/diskspace) | column -s $'\t' -t

echo ""

paste <(. ./scripts/middle/sysinfo) <(. ./scripts/middle/services) | column -s $'\t' -t

echo ""

#paste <(. ./scripts/bottom/diskstatus)
