#!/bin/bash

# config
max_usage=90
bar_width=32
disks=(/dev/mapper/cryptroot_root /dev/sda1_Data)
# colors
white="\e[39m"
green="\e[1;32m"
red="\e[1;31m"
dim="\e[2m"
undim="\e[0m"

printf "\n  ${color_title}Disk usage:${ansi_reset}\n"

#for line in "${dfs[@]}"; do
for disk in "${disks[@]}"; do
	disk=($(echo $disk | tr "_" "\n"))
	line=$(df -H --output=target,pcent,size "${disk[0]}"| tail -n 1)
    # get disk usage
    usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')
    used_width=$((($usage*$bar_width)/100))
    # color is green if usage < max_usage, else red
    if [ "${usage}" -ge "${max_usage}" ]; then
        color=$red
    else
        color=$green
    fi
    # print green/red bar until used_width
    bar="[${color}"
    for ((i=0; i<$used_width; i++)); do
        bar+="="
    done
    # print dimmmed bar until end
    bar+="${white}${dim}"
    for ((i=$used_width; i<$bar_width; i++)); do
        bar+="="
    done
    bar+="${undim}]"
    # print usage line & bar
    echo "${disk[1]} ${line}" | awk '{ printf("%-13s%+3s used out of %+4s\n", $1, $3, $4); }' | sed -e 's/^/  /'
    echo -e "${bar}" | sed -e 's/^/  /'
done
