#!/bin/bash

# config
max_usage=90
bar_width=20
# colors
white="\e[39m"
green="\e[1;32m"
red="\e[1;31m"
dim="\e[2m"
undim="\e[0m"

# disk usage: ignore zfs, squashfs & tmpfs
#mapfile -t dfs < <(df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size | tail -n+2)

pc=$(free | grep Mem | awk '{print $3/$2 * 100.0}' | sed s/\.[0-9]*$//)
used_width=$((($pc*$bar_width)/100))
# color is green if usage < max_usage, else red
if [ "${pc}" -ge "${max_usage}" ]; then
    color=$red
else
    color=$green
fi
# print green/red bar until used_width
bar="[${color}"
for ((i=0; i<$used_width; i++)); do
    bar+="="
done
# print dimmmed bar until end
bar+="${white}${dim}"
for ((i=$used_width; i<$bar_width; i++)); do
    bar+="="
done
bar+="${undim}]"

ppc="${color}${pc}%${undim}"
# print usage line & bar
echo -e "${color_subtitle}Memory${ansi_reset}: ${ppc} ${bar}"
